version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd projects/project-1-danevosmeier/project-1-ui
      - npm install
    build:
      commands:
        -npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'projects/project-1-danevosmeier/project-1-ui'